version: '3'

services:
  api:
    build: .
    restart: on-failure:10
    container_name: movie_app_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    container_name: movie_app_psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movie
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
