# Generated by Django 2.2.4 on 2019-09-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('movie', '0003_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist', verbose_name='Artist')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Job', verbose_name='Job')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Movie & Artist',
                'verbose_name_plural': 'Movie & Artists',
                'db_table': 'movie_artist',
                'ordering': ('job',),
                'unique_together': {('movie', 'artist', 'job')},
            },
        ),
    ]
