# Generated by Django 2.2.4 on 2019-09-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movieartist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieartist',
            options={'ordering': ('-movie__release_date', 'id'), 'verbose_name': 'Movie & Artist', 'verbose_name_plural': 'Movie & Artists'},
        ),
    ]
