# Generated by Django 2.2.4 on 2019-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Parameter key')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Parameter value')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'db_table': 'parameters',
                'ordering': ('key',),
            },
        ),
    ]
